import { Question, Language } from '@/types';

const questionsDatabase: Record<Language, Question[]> = {
  en: [
    {
      id: 1,
      question: 'What is the best way to protect your phone from unauthorized access?',
      options: ['Leave it unlocked', 'Use a strong password or PIN', 'Share your password with friends', 'Never lock it'],
      correctAnswer: 1,
      category: 'security',
    },
    {
      id: 2,
      question: 'What does Wi-Fi allow you to do?',
      options: ['Make calls only', 'Connect to the internet wirelessly', 'Charge your phone', 'Take photos'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 3,
      question: 'Which of these is safest when receiving messages from unknown numbers?',
      options: ['Click all links immediately', 'Share personal information', 'Be cautious and verify sender', 'Reply with bank details'],
      correctAnswer: 2,
      category: 'safety',
    },
    {
      id: 4,
      question: 'What is a common way to pay for items online?',
      options: ['Shouting at phone', 'Mobile money or card payment', 'Sending cash by post', 'Waving phone at screen'],
      correctAnswer: 1,
      category: 'payments',
    },
    {
      id: 5,
      question: 'What should you do if you forget your password?',
      options: ['Give up and buy new phone', 'Use password recovery option', 'Tell everyone your problem', 'Throw phone away'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 6,
      question: 'What is the purpose of mobile data?',
      options: ['To make phone heavier', 'To access internet when no Wi-Fi', 'To change phone color', 'To play music'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 7,
      question: 'Which app is commonly used for sending instant messages?',
      options: ['Calculator', 'WhatsApp', 'Weather app', 'Clock'],
      correctAnswer: 1,
      category: 'social',
    },
    {
      id: 8,
      question: 'What should you check before installing an app?',
      options: ['Phone color', 'App permissions and reviews', 'Weather forecast', 'Your age'],
      correctAnswer: 1,
      category: 'safety',
    },
    {
      id: 9,
      question: 'How can you save battery life on your phone?',
      options: ['Keep screen bright always', 'Close unused apps and lower brightness', 'Install more apps', 'Never turn off phone'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 10,
      question: 'What is phishing?',
      options: ['A type of fish', 'Scam to steal personal information', 'A phone game', 'A way to catch fish'],
      correctAnswer: 1,
      category: 'safety',
    },
  ],
  yo: [
    {
      id: 1,
      question: 'Kí ni ọ̀nà tó dára jù láti dáàbò bo fóònù rẹ kúrò lọ́wọ́ àwọn tí kò ní àṣẹ?',
      options: ['Fi sílẹ̀ láì sí ìdè', 'Lo ọ̀rọ̀-ìpamọ́ tàbí PIN tó lágbára', 'Pin ọ̀rọ̀-ìpamọ́ rẹ pẹ̀lú àwọn ọ̀rẹ́', 'Má ṣe tí i'],
      correctAnswer: 1,
      category: 'security',
    },
    {
      id: 2,
      question: 'Kí ni WiFi ń jẹ́ kí o ṣe?',
      options: ['Pe nìkan', 'So mọ́ íńtánẹ́ẹ̀tì láì lò wáyà', 'Gbá fóònù rẹ sí ina', 'Ya àwòrán'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 3,
      question: 'Èwo nínú àwọn wọ̀nyí ló ṣe àìléwu jù nígbà tí o bá ń gba ifiránṣẹ́ láti ọ̀dọ̀ nọ́mbà àìmọ̀?',
      options: ['Tẹ gbogbo ìjápọ̀ lẹ́sẹ̀kẹsẹ̀', 'Pin àlàyé ìkọ̀kọ̀', 'Ṣọ́ra kí o sì ṣàyẹ̀wò olùfìránṣẹ́', 'Dáhùn pẹ̀lú àlàyé bánkì'],
      correctAnswer: 2,
      category: 'safety',
    },
    {
      id: 4,
      question: 'Kí ni ọ̀nà tó wọ́pọ̀ láti san owó fún ohun lórí íńtánẹ́ẹ̀tì?',
      options: ['Kígbe sí fóònù', 'Owó móbáìlì tàbí ìsanwó káàdì', 'Fi owó sínú lẹ́tà', 'Jù fóònù sí ojú-ìwé'],
      correctAnswer: 1,
      category: 'payments',
    },
    {
      id: 5,
      question: 'Kí ni o yẹ kí o ṣe tí o bá gbàgbé ọ̀rọ̀-ìpamọ́ rẹ?',
      options: ['Jáwọ́ kí o sì ra fóònù tuntun', 'Lo ẹ̀yà ìmúpadàbọ̀ ọ̀rọ̀-ìpamọ́', 'Sọ fún gbogbo ènìyàn', 'Ju fóònù nù'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 6,
      question: 'Kí ni ìdí data móbáìlì?',
      options: ['Láti jẹ́ kí fóònù wúwo', 'Láti wọ íńtánẹ́ẹ̀tì nígbà tí kò bá sí WiFi', 'Láti yí àwọ̀ fóònù padà', 'Láti ṣe orin'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 7,
      question: 'Ète wo ni a máa ń lò fún fífi ifiránṣẹ́ ránṣẹ́ lẹ́sẹ̀kẹsẹ̀?',
      options: ['Kálíkúlétọ̀', 'WhatsApp', 'Ète ojú-ọjọ́', 'Àgogo'],
      correctAnswer: 1,
      category: 'social',
    },
    {
      id: 8,
      question: 'Kí ni o yẹ kí o ṣàyẹ̀wò ṣáájú kí o tó fi ète sọ́rí ẹ̀rọ?',
      options: ['Àwọ̀ fóònù', 'Àwọn àṣẹ àti àwọn àgbéyẹ̀wò ète', 'Àsọtẹ́lẹ̀ ojú-ọjọ́', 'Ọjọ́ orí rẹ'],
      correctAnswer: 1,
      category: 'safety',
    },
    {
      id: 9,
      question: 'Báwo ni o ṣe lè tọ́jú agbára bátírì fóònù rẹ?',
      options: ['Jẹ́ kí ojú-ìwé tan nígbà gbogbo', 'Pa àwọn ète tí o kò lò kí o sì dín ìmọ́lẹ̀ kù', 'Fi ète púpọ̀ sínú', 'Má ṣe pa fóònù'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 10,
      question: 'Kí ni phishing?',
      options: ['Irú ẹja kan', 'Ìtànjẹ láti jí àlàyé ìkọ̀kọ̀', 'Eré fóònù', 'Ọ̀nà láti mu ẹja'],
      correctAnswer: 1,
      category: 'safety',
    },
  ],
  ha: [
    {
      id: 1,
      question: 'Menene hanya mafi kyau don kare wayar ku daga shiga ba tare da izini ba?',
      options: ['Bar ta a buɗe', 'Yi amfani da kalmar sirri mai ƙarfi ko PIN', 'Raba kalmar sirrin ku da abokai', 'Kada ku taɓa kullewa'],
      correctAnswer: 1,
      category: 'security',
    },
    {
      id: 2,
      question: 'Me WiFi ke bawa ku damar yi?',
      options: ['Yin kira kawai', 'Haɗa zuwa intanet ba tare da waya ba', 'Caja wayar ku', 'Ɗaukar hotuna'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 3,
      question: 'Wannene mafi aminci lokacin karɓar saƙonni daga lambobin da ba ku sani ba?',
      options: ['Danna duk hanyoyin haɗi nan take', 'Raba bayanan sirri', 'Ku kasance masu hankali ku tabbatar da mai aikawa', 'Amsa da bayanan banki'],
      correctAnswer: 2,
      category: 'safety',
    },
    {
      id: 4,
      question: 'Menene hanyar da ake amfani da ita wajen biyan kayan kan layi?',
      options: ['Yin ihu a waya', 'Kuɗin wayar hannu ko biyan kuɗi da kati', 'Aika kuɗi ta wasiƙa', 'Kada waya akan allo'],
      correctAnswer: 1,
      category: 'payments',
    },
    {
      id: 5,
      question: 'Me ya kamata ku yi idan kun manta da kalmar sirrin ku?',
      options: ['Ku daina ku sayi sabuwar waya', 'Yi amfani da zaɓin dawo da kalmar sirri', 'Faɗa wa kowa matsalar ku', 'Jefar da waya'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 6,
      question: 'Menene manufar data ta wayar hannu?',
      options: ['Don yin waya mafi nauyi', 'Don samun intanet idan babu WiFi', 'Don canza launin waya', 'Don kunna kiɗa'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 7,
      question: 'Wane app ne ake yawan amfani da shi wajen aika saƙon nan take?',
      options: ['Calculator', 'WhatsApp', 'App na yanayi', 'Agogo'],
      correctAnswer: 1,
      category: 'social',
    },
    {
      id: 8,
      question: 'Me ya kamata ku duba kafin ku shigar da app?',
      options: ['Launin waya', 'Izinin app da sharhi', 'Hasashen yanayi', 'Shekarun ku'],
      correctAnswer: 1,
      category: 'safety',
    },
    {
      id: 9,
      question: 'Ta yaya za ku iya ajiye rayuwar batur wayar ku?',
      options: ['Ku bar allo ya yi haske koyaushe', 'Rufe apps da ba ku amfani da su ba ku rage haske', 'Shigar da ƙarin apps', 'Kada ku kashe waya'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 10,
      question: 'Menene phishing?',
      options: ['Irin kifi', 'Zamba don satar bayanan sirri', 'Wasan waya', 'Hanyar kama kifi'],
      correctAnswer: 1,
      category: 'safety',
    },
  ],
  ig: [
    {
      id: 1,
      question: 'Kedu ụzọ kacha mma iji chebe ekwentị gị site n\'aka ndị na-enweghị ikike?',
      options: ['Hapụ ya ka ọ bụrụ emeghe', 'Jiri okwuntughe siri ike ma ọ bụ PIN', 'Kesaa okwuntughe gị na ndị enyi', 'Ejila ya mkpọchi'],
      correctAnswer: 1,
      category: 'security',
    },
    {
      id: 2,
      question: 'Kedu ihe WiFi na-eme ka i mee?',
      options: ['Kpọọ oku naanị', 'Jikọọ na ịntanetị na-enweghị waya', 'Chajie ekwentị gị', 'See foto'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 3,
      question: 'Kedu nke n\'ime ndị a kacha nchekwa mgbe ị na-anata ozi sitere na nọmba ndị a na-amaghị?',
      options: ['Pịa njikọ niile ozugbo', 'Kesaa ozi nkeonwe', 'Kpachara anya wee chọpụta onye ziri', 'Zaghachi ya na nkọwa ụlọ akụ'],
      correctAnswer: 2,
      category: 'safety',
    },
    {
      id: 4,
      question: 'Kedu ụzọ a na-ejikarị akwụ ụgwọ maka ihe dị n\'ịntanetị?',
      options: ['Itiri mkpu na ekwentị', 'Ego ekwentị ma ọ bụ ịkwụ ụgwọ kaadị', 'Izipu ego site na akwụkwọ ozi', 'Ifegharị ekwentị n\'ihuenyo'],
      correctAnswer: 1,
      category: 'payments',
    },
    {
      id: 5,
      question: 'Gịnị ka ị ga-eme ma ọ bụrụ na ị chefuo okwuntughe gị?',
      options: ['Kwụsị wee zụta ekwentị ọhụrụ', 'Jiri nhọrọ nwetaghachi okwuntughe', 'Gwa mmadụ niile nsogbu gị', 'Tufuo ekwentị'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 6,
      question: 'Gịnị bụ ebumnuche data ekwentị?',
      options: ['Ime ka ekwentị dị arọ', 'Inweta ịntanetị mgbe enweghị WiFi', 'Ịgbanwe agba ekwentị', 'Ịgba egwu'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 7,
      question: 'Kedu ngwa a na-ejikarị ezipu ozi ngwa ngwa?',
      options: ['Kalkuleta', 'WhatsApp', 'Ngwa ihu igwe', 'Elekere'],
      correctAnswer: 1,
      category: 'social',
    },
    {
      id: 8,
      question: 'Gịnị ka ị kwesịrị ịlele tupu i wụnye ngwa?',
      options: ['Agba ekwentị', 'Ikike ngwa na nyocha', 'Amụma ihu igwe', 'Afọ ole ị dị'],
      correctAnswer: 1,
      category: 'safety',
    },
    {
      id: 9,
      question: 'Kedu otu i si echekwa ndụ batrị ekwentị gị?',
      options: ['Mee ka ihuenyo na-enwu mgbe niile', 'Mechie ngwa ndị a na-adịghị eji wee belata ìhè', 'Wụnye ngwa ndị ọzọ', 'Ejila gbanyụọ ekwentị'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 10,
      question: 'Gịnị bụ phishing?',
      options: ['Ụdị azụ̀', 'Aghụghọ iji zuru ozi nkeonwe', 'Egwuregwu ekwentị', 'Ụzọ iji jide azụ̀'],
      correctAnswer: 1,
      category: 'safety',
    },
  ],
  pcm: [
    {
      id: 1,
      question: 'Wetin be the best way to protect your phone make person wey no get right no fit enter?',
      options: ['Leave am unlock', 'Use strong password or PIN', 'Share your password with friends', 'No lock am at all'],
      correctAnswer: 1,
      category: 'security',
    },
    {
      id: 2,
      question: 'Wetin WiFi dey allow you do?',
      options: ['Make call only', 'Connect to internet without wire', 'Charge your phone', 'Take picture'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 3,
      question: 'Which one safe pass when you dey receive message from number wey you no sabi?',
      options: ['Click all links sharp sharp', 'Share personal information', 'Take your time check who send am', 'Reply with bank details'],
      correctAnswer: 2,
      category: 'safety',
    },
    {
      id: 4,
      question: 'Wetin be common way to pay for things online?',
      options: ['Shout for phone', 'Mobile money or card payment', 'Send cash by post', 'Wave phone for screen'],
      correctAnswer: 1,
      category: 'payments',
    },
    {
      id: 5,
      question: 'Wetin you suppose do if you forget your password?',
      options: ['Give up buy new phone', 'Use password recovery option', 'Tell everybody your problem', 'Throw phone away'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 6,
      question: 'Wetin be the work of mobile data?',
      options: ['To make phone heavy', 'To use internet when no WiFi dey', 'To change phone color', 'To play music'],
      correctAnswer: 1,
      category: 'internet',
    },
    {
      id: 7,
      question: 'Which app dem dey use well well to send instant message?',
      options: ['Calculator', 'WhatsApp', 'Weather app', 'Clock'],
      correctAnswer: 1,
      category: 'social',
    },
    {
      id: 8,
      question: 'Wetin you suppose check before you install app?',
      options: ['Phone color', 'App permissions and reviews', 'Weather forecast', 'Your age'],
      correctAnswer: 1,
      category: 'safety',
    },
    {
      id: 9,
      question: 'How you fit save battery life for your phone?',
      options: ['Make screen bright always', 'Close apps wey you no dey use and reduce brightness', 'Install more apps', 'Never off phone'],
      correctAnswer: 1,
      category: 'basic',
    },
    {
      id: 10,
      question: 'Wetin be phishing?',
      options: ['Type of fish', 'Scam to thief personal information', 'Phone game', 'Way to catch fish'],
      correctAnswer: 1,
      category: 'safety',
    },
  ],
};

export function getQuestions(language: Language): Question[] {
  return questionsDatabase[language] || questionsDatabase.en;
}

export function getQuestionFromAgent(metrics: any, language: Language): Question[] {
  return getQuestions(language);
}
